# Generated by Django 3.2.8 on 2022-05-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='describtion',
            field=models.CharField(default='describtion', max_length=300),
        ),
        migrations.AlterField(
            model_name='paper',
            name='link',
            field=models.CharField(default='link', max_length=300),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(default='paper', max_length=300),
        ),
        migrations.AlterField(
            model_name='paper',
            name='publishdate',
            field=models.CharField(default='date', max_length=30),
        ),
    ]
