# Generated by Django 3.2.8 on 2022-05-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220501_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='imgsrc',
            field=models.CharField(default='imgsrc', max_length=300),
        ),
    ]
