# Generated by Django 3.2.8 on 2022-05-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_paper_imgsrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Databases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(default='database', max_length=50)),
                ('description', models.CharField(default='description', max_length=300)),
                ('institute', models.CharField(default='institute', max_length=200)),
                ('version', models.CharField(default='version', max_length=100)),
                ('numoflncrna', models.CharField(default='numoflncrna', max_length=50)),
                ('spieces', models.CharField(default='spieces', max_length=50)),
            ],
        ),
    ]
