# Generated by Django 3.2.8 on 2022-05-03 14:35

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_databases'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=10)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
