# Generated by Django 3.2.8 on 2022-05-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='latestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(default='paperid', max_length=15)),
                ('title', models.CharField(default='title', max_length=200)),
                ('paperurl', models.CharField(default='paper', max_length=300)),
                ('link', models.CharField(default='link', max_length=300)),
                ('journal_name', models.CharField(default='journal_name', max_length=300)),
                ('year', models.CharField(default='year', max_length=10)),
                ('imgsrc', models.CharField(default='imgsrc', max_length=300)),
            ],
        ),
    ]
