# Generated by Django 3.2.8 on 2022-05-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_latestpaper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestpaper',
            name='link',
        ),
    ]
