# Generated by Django 3.2.8 on 2022-05-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_latestpaper_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='date',
            field=models.IntegerField(default='1'),
        ),
    ]
