# Generated by Django 3.2.8 on 2022-05-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_paper_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pid',
            field=models.CharField(default='pid', max_length=10),
        ),
    ]
