# Generated by Django 3.2.8 on 2022-05-09 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_paper_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='citations',
            field=models.IntegerField(default='0'),
        ),
    ]
